# Generated by Django 3.1.6 on 2021-02-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revendedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDRevendedor', models.PositiveIntegerField()),
                ('Nome', models.CharField(max_length=2147483647)),
                ('CPF', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Senha', models.PositiveIntegerField()),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
