# Generated by Django 3.1.6 on 2021-02-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Revendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDPedidos', models.PositiveIntegerField()),
                ('Valor_Total', models.PositiveIntegerField()),
                ('Porcentagem_Cashback', models.PositiveIntegerField()),
                ('Data', models.DateField(max_length=10)),
                ('Status', models.CharField(max_length=50)),
                ('IDRevendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revendedores.revendedores')),
            ],
        ),
    ]
