# Generated by Django 3.1.6 on 2021-02-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Revendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedidos', models.PositiveIntegerField()),
                ('valor_total', models.PositiveIntegerField()),
                ('porcentagem_cashback', models.PositiveIntegerField()),
                ('data', models.DateField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('id_revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revendedores.revendedores')),
            ],
        ),
    ]
